// <auto-generated />
namespace Destinos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _09apr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_09apr));
        
        string IMigrationMetadata.Id
        {
            get { return "202404091017598_09apr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
